name: deploy-livia-prod-2-useast
on:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment: livia-prod-2-useast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync repo to server (~/livia)
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: ${{ secrets.APP_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
            cd ${{ secrets.APP_DIR }}
            # pull latest image for arm64
            docker pull ghcr.io/${{ secrets.GHCR_ORG }}/${{ secrets.IMAGE_NAME }}:latest || true
            # bring up your compose stack (adjust filenames as you add them)
            if [ -f infra/compose/app.compose.yml ]; then
              cd infra/compose
              docker compose -f app.compose.yml pull || true
              docker compose -f app.compose.yml up -d --remove-orphans
            fi
            docker image prune -f